'use strict';
window.OFFER=(()=>{
const icons={arrow:'<path d="M4 10h12m-5-5 5 5-5 5"/>',up:'<path d="M5 15 15 5M5 5h10v10"/>',search:'<circle cx="8.5" cy="8.5" r="5.5"/><path d="m13 13 4 4"/>',heart:'<path d="M17.4 4.1a4.3 4.3 0 0 0-6.1 0L10 5.4 8.7 4.1a4.3 4.3 0 0 0-6.1 6.1L10 17.5l7.4-7.3a4.3 4.3 0 0 0 0-6.1Z"/>',menu:'<path d="M3 6h14M3 14h14"/>',plus:'<path d="M4 10h12M10 4v12"/>',check:'<path d="m4 10 4 4 8-8"/>'};
const icon=name=>'<svg class="icon" viewBox="0 0 20 20" aria-hidden="true">'+(icons[name]||icons.arrow)+'</svg>';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const memory={};let storageUnavailable=false;
const read=key=>{if(storageUnavailable)return memory[key]||[];try{const a=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(a)?a.filter(x=>typeof x==='string'):[];}catch{return memory[key]||[];}};
const has=(key,id)=>read(key).includes(id);
function toggle(key,id){let list=read(key);list=list.includes(id)?list.filter(x=>x!==id):[...list,id];memory[key]=list;let stored=true;try{localStorage.setItem(key,JSON.stringify(list));}catch{stored=false;storageUnavailable=true;}document.dispatchEvent(new CustomEvent('offer:storage',{detail:{key,id}}));toast(stored?(key==='savedOffers'?(list.includes(id)?'OFFER를 저장했습니다.':'저장을 해제했습니다.'):(list.includes(id)?'관심 브랜드에 추가했습니다.':'관심 브랜드에서 삭제했습니다.')):'브라우저 저장 공간을 사용할 수 없어 이 화면에서만 반영됩니다.');return list.includes(id);}
const day=s=>{const [y,m,d]=s.split('-').map(Number);return Date.UTC(y,m-1,d);};
function today(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const v=t=>parts.find(x=>x.type===t).value;return day(v('year')+'-'+v('month')+'-'+v('day'));}
const remaining=p=>Math.round((day(p.period.end)-today())/86400000);
const active=p=>day(p.period.start)<=today()&&remaining(p)>=0;
function status(p){const d=remaining(p);if(d<0)return {text:'종료',urgent:false};if(day(p.period.start)>today())return {text:'예정',urgent:false};return {text:d===0?'D-DAY':'D-'+d,urgent:d<=3};}
const date=s=>s.slice(5).replace('-','.');
const badge=p=>{const s=status(p);return '<span class="status '+(s.urgent?'urgent':'')+'">'+s.text+'</span>';};
function saveButton(p,detail=false){const saved=has('savedOffers',p.id);return '<button type="button" class="'+(detail?'button button-secondary detail-save':'card-save')+'" data-save="'+escape(p.id)+'" aria-pressed="'+saved+'" aria-label="'+escape(p.title)+(saved?' 저장 해제':' 저장')+'">'+icon('heart')+(detail?'<span>'+(saved?'저장한 OFFER':'OFFER 저장하기')+'</span>':'')+'</button>';}
function card(p,variant=''){const url='offer.html?id='+encodeURIComponent(p.id);return '<article class="offer-card '+(variant?'offer-card--'+variant:'')+'"><a class="card-image-link" href="'+url+'" tabindex="-1" aria-hidden="true"><img class="card-image" src="'+escape(p.image)+'" alt="" loading="lazy" width="800" height="600"></a>'+saveButton(p)+'<div class="card-body"><a class="card-brand" href="brand.html?id='+escape(p.brandId)+'">'+escape(p.brandName)+'</a><h3 class="card-title"><a href="'+url+'">'+escape(p.title)+'</a></h3><div class="card-meta"><span class="discount">'+escape(p.discount.label)+'</span>'+badge(p)+'</div><p class="card-date"><time datetime="'+p.period.start+'">'+date(p.period.start)+'</time> — <time datetime="'+p.period.end+'">'+date(p.period.end)+'</time></p></div></article>';}
const grid=(items,three=false,variant='')=>'<div class="offer-grid '+(three?'three-col':'')+'">'+items.map(p=>card(p,variant)).join('')+'</div>';
const empty=(title,text,href='explore.html',label='OFFER 둘러보기')=>'<div class="empty-state"><div><h3>'+escape(title)+'</h3><p>'+escape(text)+'</p></div><a class="button button-primary" href="'+href+'">'+label+icon('arrow')+'</a></div>';
function searchForm(value='',id='search'){return '<form class="search-form" action="explore.html" role="search"><label class="sr-only" for="'+id+'">브랜드 또는 이벤트 검색</label><input id="'+id+'" name="q" type="search" placeholder="브랜드 또는 이벤트 검색" value="'+escape(value)+'" autocomplete="off"><button class="icon-button" type="submit" aria-label="검색">'+icon('search')+'</button></form>';}
const categories=[['all','All'],['fashion','Fashion'],['beauty','Beauty'],['food','Food'],['lifestyle','Lifestyle']];
function filters(current='all'){return '<div class="filters" aria-label="카테고리">'+categories.map(([id,label])=>'<button class="filter" data-category="'+id+'" aria-pressed="'+(id===current)+'">'+label+'</button>').join('')+'</div>';}
const brandLogo=b=>'<span class="brand-logo" style="background:'+escape(b.logoBackground)+'"><img src="'+escape(b.logo)+'" alt="" width="120" height="64" loading="lazy"></span>';
function followButton(b,chip=false){const on=has('favoriteBrands',b.id);return '<button class="'+(chip?'brand-chip':'button button-secondary')+'" data-follow="'+b.id+'" aria-pressed="'+on+'" aria-label="'+escape(b.name)+(on?' 관심 해제':' 팔로우')+'">'+(chip?brandLogo(b)+'<span>'+escape(b.name)+'</span>':(on?'팔로잉':'팔로우'))+icon(on?'check':'plus')+'</button>';}
let timer;
function toast(message){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>el.classList.remove('visible'),3200);}
function sync(){document.querySelectorAll('[data-save]').forEach(el=>{const on=has('savedOffers',el.dataset.save);el.setAttribute('aria-pressed',on);const p=OFFER_DATA.promotions.find(p=>p.id===el.dataset.save);el.setAttribute('aria-label',(p?.title||'OFFER')+(on?' 저장 해제':' 저장'));if(el.classList.contains('detail-save'))el.querySelector('span').textContent=on?'저장한 OFFER':'OFFER 저장하기';});document.querySelectorAll('[data-follow]').forEach(el=>{const b=OFFER_DATA.brands.find(b=>b.id===el.dataset.follow);if(b){const replacement=document.createElement('template');replacement.innerHTML=followButton(b,el.classList.contains('brand-chip'));const n=replacement.content.firstChild;el.innerHTML=n.innerHTML;el.setAttribute('aria-pressed',n.getAttribute('aria-pressed'));el.setAttribute('aria-label',n.getAttribute('aria-label'));}});}
function shell(){const page=document.body.dataset.page;document.getElementById('site-header').innerHTML='<div class="container header-inner"><a class="wordmark" href="index.html" aria-label="OFFER 홈">OFFER</a><nav class="header-nav" id="main-nav" aria-label="주 메뉴">'+[['explore','Explore'],['saved','Saved'],['favorites','Favorites']].map(([id,label])=>'<a href="'+id+'.html" '+(page===id?'aria-current="page"':'')+'>'+label+'</a>').join('')+'</nav><div class="header-actions"><a class="icon-button" href="explore.html?focus=search" aria-label="검색 열기">'+icon('search')+'</a><button class="icon-button menu-toggle" aria-label="메뉴 열기" aria-controls="main-nav" aria-expanded="false">'+icon('menu')+'</button></div></div>';
document.getElementById('site-footer').innerHTML='<div class="container"><div class="footer-top"><div><a class="wordmark" href="index.html">OFFER</a><p>Different brands. Better discoveries.</p></div><nav class="footer-links" aria-label="하단 메뉴"><a href="/#work">← 포트폴리오</a><a href="explore.html">Explore</a><a href="saved.html">Saved OFFERs</a><a href="favorites.html">Favorite Brands</a></nav></div><div class="footer-bottom"><p class="footer-disclaimer">포트폴리오 데모 · 모든 혜택과 일정은 가상 샘플입니다.<br>실제 진행 중인 프로모션이 아니며, 브랜드 링크는 공식 홈페이지로 연결됩니다.</p><p>© 2026 OFFER — A discovery project.</p></div></div>';
const menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기');document.getElementById('main-nav').classList.toggle('is-open',open);});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){menu.click();menu.focus();}});window.addEventListener('scroll',()=>document.getElementById('site-header').classList.toggle('scrolled',scrollY>16),{passive:true});
document.addEventListener('click',e=>{if(menu.getAttribute('aria-expanded')==='true'&&!document.getElementById('site-header').contains(e.target))menu.click();const save=e.target.closest('[data-save]'),follow=e.target.closest('[data-follow]');if(save)toggle('savedOffers',save.dataset.save);if(follow)toggle('favoriteBrands',follow.dataset.follow);});
matchMedia('(min-width: 768px)').addEventListener('change',e=>{if(e.matches&&menu.getAttribute('aria-expanded')==='true')menu.click();});
document.addEventListener('offer:storage',sync);window.addEventListener('storage',()=>{storageUnavailable=false;sync();document.dispatchEvent(new CustomEvent('offer:external-storage'));});}
return {icon,escape,read,has,toggle,day,today,remaining,active,status,date,badge,card,grid,empty,searchForm,filters,brandLogo,followButton,toast,shell};
})();
OFFER.shell();
/* Optional browser-native agent access to the same save action. */
offerReady.then(({promotions})=>{
if(!document.modelContext?.registerTool)return;
const lifecycle=new AbortController();
try{Promise.resolve(document.modelContext.registerTool({
name:'set_saved_offers',title:'Save or remove OFFERs',
description:'Set the saved state of specified demo OFFERs in this browser and update the visible interface.',
inputSchema:{type:'object',properties:{ids:{type:'array',items:{type:'string'},minItems:1,maxItems:20},saved:{type:'boolean'}},required:['ids','saved'],additionalProperties:false},
annotations:{readOnlyHint:false,untrustedContentHint:false},
execute(input){if(!input||!Array.isArray(input.ids)||!input.ids.length||input.ids.length>20||typeof input.saved!=='boolean'||Object.keys(input).some(k=>!['ids','saved'].includes(k))||input.ids.some(id=>typeof id!=='string'||!promotions.some(p=>p.id===id)))throw new Error('Provide valid OFFER IDs and a boolean saved state.');for(const id of new Set(input.ids)){if(OFFER.has('savedOffers',id)!==input.saved)OFFER.toggle('savedOffers',id);}return {savedOffers:OFFER.read('savedOffers')};}
},{signal:lifecycle.signal})).catch(()=>{});}catch{}
window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
});