const {chromium}=require('C:/Users/SBS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),out=path.join(__dirname,'qa-card-flow');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),report={};try{
 const p=await b.newPage({viewport:{width:1440,height:1000}});await p.route('https://cdn.jsdelivr.net/**',r=>r.abort());await p.goto('http://127.0.0.1:4173/#work',{waitUntil:'domcontentloaded'});await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(150);await p.keyboard.press('Shift');
 const center=async i=>{await p.evaluate(i=>{const w=document.querySelector('#work');scrollTo({top:+w.dataset.entryStart+(+w.dataset.intro)+(+w.dataset.hold)+(+w.dataset.slot)*i,behavior:'instant'});},i);await p.waitForTimeout(250);};
 await center(3);const end=await p.evaluate(()=>scrollY);await p.mouse.wheel(0,240);await p.waitForTimeout(750);assert((await p.evaluate(()=>scrollY))>end+180);report.lastCoverReleases=true;
 await center(0);const beginning=await p.evaluate(()=>scrollY);await p.mouse.wheel(0,-200);await p.waitForTimeout(750);assert((await p.evaluate(()=>scrollY))<beginning-180);report.firstCoverReleases=true;
 await center(0);await p.mouse.wheel(0,70);await p.waitForTimeout(50);await p.locator('.monogram').click();await p.waitForFunction(()=>!document.querySelector('.portfolio-intro'));assert.equal(await p.evaluate(()=>scrollY),0);await center(0);await p.mouse.wheel(0,70);await p.waitForTimeout(750);assert.equal(+(await p.locator('#work').getAttribute('data-position')),1);report.interruptionAndReplay=true;
 for(const i of [0,1,2,3]){await center(i);const href=await p.locator('.work-current-link').getAttribute('href');await p.locator('.work-current-link').focus();await p.keyboard.press('Enter');await p.waitForURL('**'+href,{waitUntil:'domcontentloaded'});await p.goBack({waitUntil:'domcontentloaded'});await p.waitForTimeout(300);assert.equal(+(await p.locator('#work').getAttribute('data-current')),i);}report.keyboardLinks=true;
 const mobile=await b.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await mobile.route('https://cdn.jsdelivr.net/**',r=>r.abort());await mobile.goto('http://127.0.0.1:4173/#qa',{waitUntil:'domcontentloaded'});await mobile.evaluate(()=>document.fonts.ready);await mobile.keyboard.press('Shift');await mobile.evaluate(()=>{const q=document.querySelector('#qa');scrollTo({top:+q.dataset.entryStart+(+q.dataset.entryDistance),behavior:'instant'});});await mobile.waitForTimeout(1600);
 const deck=mobile.locator('.qa-deck');await deck.scrollIntoViewIfNeeded();await mobile.waitForTimeout(200);const box=await deck.boundingBox(),cdp=await mobile.context().newCDPSession(mobile),x=box.x+box.width*.85,y=Math.min(650,Math.max(150,box.y+box.height*.5));console.log('DECK',box,{x,y},await deck.evaluate(el=>({width:el.clientWidth,scrollWidth:el.scrollWidth,overflow:getComputedStyle(el).overflowX,touchAction:getComputedStyle(el).touchAction})));console.log('HIT',await mobile.evaluate(({x,y})=>document.elementFromPoint(x,y)?.outerHTML.slice(0,120),{x,y}));await mobile.screenshot({path:path.join(out,'390-touch-before.png')});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let step=1;step<=10;step++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-box.width*.65*step/10,y}]});await new Promise(resolve=>setTimeout(resolve,25));}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mobile.waitForTimeout(350);const touchState=await deck.evaluate(el=>({scrollLeft:el.scrollLeft,pointerEvents:getComputedStyle(el).pointerEvents}));console.log('TOUCH',touchState);assert(touchState.scrollLeft>0);report.touchHorizontal=true; for(let swipeIndex=0;swipeIndex<3;swipeIndex++){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let step=1;step<=10;step++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-box.width*.65*step/10,y}]});await new Promise(resolve=>setTimeout(resolve,25));}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mobile.waitForTimeout(350);}await mobile.waitForTimeout(1400);const lastTouch=await mobile.locator('.qa-card').nth(4).boundingBox();assert(lastTouch.x>=20&&lastTouch.x+lastTouch.width<=390);await mobile.screenshot({path:path.join(out,'390-touch-last.png')});report.touchLastCard=true;
 await mobile.evaluate(async()=>{const img=document.querySelector('.qa-card--diamond img');img.loading='eager';await img.decode();document.querySelector('.qa-card--diamond').focus();});await mobile.waitForTimeout(150);await mobile.screenshot({path:path.join(out,'390-touch-diamond.png')});
 await p.goto('http://127.0.0.1:4173/#qa',{waitUntil:'domcontentloaded'});await p.evaluate(()=>document.fonts.ready);await p.locator('.qa-card--diamond').focus();await p.waitForTimeout(200);await p.locator('.qa-card--diamond').screenshot({path:path.join(out,'1440-diamond-final.png')});
 fs.writeFileSync(path.join(out,'interaction-report.json'),JSON.stringify(report,null,2));console.log('PASS',JSON.stringify(report));
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
